# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-11 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vts_squad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yamltemplate',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
