# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-11 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vts_squad', '0002_yamltemplate_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='LavaDeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('lava_server_host', models.CharField(default='10.0.70.142', max_length=32)),
            ],
        ),
    ]
