# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-13 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vts_squad', '0007_auto_20181213_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delployimgs',
            name='description',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='delployimgs',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
