# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-13 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vts_squad', '0009_delployimgs_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delployimgs',
            name='img',
            field=models.CharField(default='', max_length=32),
        ),
    ]
