# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-13 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vts_squad', '0011_auto_20181213_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavadevicetype',
            name='worker05_pac',
            field=models.URLField(default=''),
        ),
    ]
