# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-13 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vts_squad', '0012_lavadevicetype_worker05_pac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavadevicetype',
            name='worker05_pac',
            field=models.CharField(default='', max_length=256),
        ),
    ]
