# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-13 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vts_squad', '0013_auto_20181213_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquadAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.CharField(default='', max_length=128)),
                ('desc', models.CharField(default='', max_length=256)),
                ('name', models.CharField(default='', max_length=32)),
            ],
        ),
    ]
