# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-13 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vts_squad', '0014_squadapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadapi',
            name='token',
            field=models.CharField(default='', max_length=128),
        ),
    ]
