# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-13 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vts_squad', '0016_auto_20181213_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squadapi',
            name='device_type',
        ),
        migrations.AddField(
            model_name='lavadevicetype',
            name='squad_api',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vts_squad.SquadAPI'),
        ),
    ]
