# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-14 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vts_squad', '0017_auto_20181213_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='compress_log',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='job',
            name='download_compress_status',
            field=models.CharField(default='Download starting', max_length=16),
        ),
        migrations.AddField(
            model_name='job',
            name='download_log',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
