# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-14 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vts_squad', '0018_auto_20181214_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='jenkins_build_interval',
        ),
        migrations.RemoveField(
            model_name='job',
            name='jenkins_pac_interval',
        ),
        migrations.RemoveField(
            model_name='job',
            name='jenkins_sync_code_interval',
        ),
        migrations.AddField(
            model_name='job',
            name='jenkins_list',
            field=models.CharField(default='', max_length=512),
        ),
    ]
