# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-14 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vts_squad', '0021_auto_20181214_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='download_compress_status',
            field=models.CharField(default='Download starting', max_length=32),
        ),
    ]
