# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-14 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vts_squad', '0022_auto_20181214_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='user',
        ),
    ]
