# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-17 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vts_squad', '0024_job_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='verify_url',
            field=models.CharField(default='', max_length=256),
        ),
    ]
