# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-19 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vts_squad', '0027_auto_20181219_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lavadevicetype',
            name='template',
        ),
        migrations.AddField(
            model_name='gonggao',
            name='fabu_or_not',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gonggao',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lavadevicetype',
            name='templates',
            field=models.TextField(default='', max_length=10240),
        ),
    ]
