# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-19 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vts_squad', '0028_auto_20181219_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lavadevicetype',
            old_name='templates',
            new_name='template',
        ),
    ]
